# Generated by Django 3.2.6 on 2021-08-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tradking', '0004_stock_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Trade',
        ),
    ]
