# Generated by Django 3.2.6 on 2021-08-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradking', '0007_alter_trade_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
